import {
  AlertCircle, AlertTriangle, AppWindow, ArrowLeft, ArrowRight, ArrowUpRight,
  Award, BadgeCheck, BarChart3, Bitcoin, Bot, BrainCircuit, Building2, Calendar, Check, CheckCircle, ChevronDown, CircleDot,
  Clapperboard, Clock, CloudUpload, Copy, CreditCard, Crop, Download, Eye,
  FileVideo, Folder, FolderOpen, Footprints, Grid3x3, Heart, History, Hourglass,
  Image, Info, Languages, LayoutDashboard, Leaf, ListChecks, Lock, Mail, Mars, Menu,
  MessageCircle, MessageSquare, Mic, Monitor, Music,   PawPrint, Pencil, Phone, Play,
  PlayCircle, Plus, RefreshCw, RotateCcw, Scissors, Search, Send, Settings,
  Share2, Shield, Sliders, Smartphone, Sparkles, Square, Star, Trash2, Trophy, Tv, User,
  UserPlus, Venus, Video, Timer, Headphones, X, Zap
} from "lucide-react";

const iconMap = {
  add: Plus,
  badge: Award,
  business: Building2,
  analytics: BarChart3,
  apps: Grid3x3,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  auto_awesome: Sparkles,
  auto_videocam: Clapperboard,
  bolt: Zap,
  brain: BrainCircuit,
  calendar_month: Calendar,
  call: Phone,
  clock: Clock,
  chat: MessageSquare,
  chat_bubble: MessageCircle,
  check: Check,
  check_circle: CheckCircle,
  checklist: ListChecks,
  close: X,
  cloud_upload: CloudUpload,
  content_copy: Copy,
  content_cut: Scissors,
  credit_card: CreditCard,
  crop_16_9: Crop,
  crop_7_5: Crop,
  crop_portrait: Crop,
  crop_square: Crop,
  currency_bitcoin: Bitcoin,
  dashboard: LayoutDashboard,
  delete: Trash2,
  delete_sweep: Trash2,
  directions_run: Footprints,
  download: Download,
  edit: Pencil,
  emoji_events: Trophy,
  enhanced_encryption: Shield,
  emoji_nature: Leaf,
  error: AlertTriangle,
  error_outline: AlertCircle,
  expand_more: ChevronDown,
  favorite: Heart,
  female: Venus,
  flare: Sparkles,
  flash_on: Zap,
  folder: Folder,
  folder_open: FolderOpen,
  group_add: UserPlus,
  history: History,
  is_favorite: Star,
  hourglass_top: Hourglass,
  image: Image,
  language: Languages,
  images: Image,
  info: Info,
  lock: Lock,
  mail: Mail,
  male: Mars,
  menu: Menu,
  movie: Video,
  music_note: Music,
  north_east: ArrowUpRight,
  person: User,
  pets: PawPrint,
  play_arrow: Play,
  play_circle: PlayCircle,
  psychology: BrainCircuit,
  record_voice_over: Mic,
  refresh: RefreshCw,
  replay: RotateCcw,
  reviews: Star,
  run_circle: CircleDot,
  schedule: Clock,
  search: Search,
  send: Send,
  settings: Settings,
  settings_input_component: Sliders,
  share: Share2,
  smart_display: Monitor,
  smart_toy: Bot,
  timer: Timer,
  smartphone: Smartphone,
  star: Star,
  stop: Square,
  support_agent: Headphones,
  tv: Tv,
  user: User,
  verified: BadgeCheck,
  video_file: FileVideo,
  videocam: Video,
  visibility: Eye,
  workspace_premium: Award,
};

export default function Icon({ name, className, size = 16, style, ...props }) {
  const LucideIcon = iconMap[name];
  if (!LucideIcon) return null;
  return <LucideIcon className={className} size={size} style={style} {...props} />;
}
